### ISSUE TITLE
MariaDB service fails due to deprecation of innodb_additional_mem_pool_size

### ISSUE THREAD

**Issue by jike212** [VitalPBX/VPS#2]
When running the VPS script, it fails when attempting to run MariaDB and generates the following line in the logs on CentOS 8:

`[ERROR] /usr/libexec/mysqld: unknown variable 'innodb_additional_mem_pool_size=16M'`

**Comment by eagle26** [comment]
The VitalPBX hasn't been homologated with Centos 8 yet.
